# -*- coding: utf-8 -*-
"""House_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gav-TUM2N9Po-2HAN59cE9V4rLTExC6P
"""

!pip install numpy matplotlib scikit-learn pandas

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import pandas as pd

df=pd.read_csv('house_prices.csv')
df.head(20)

print(df.columns)

plt.xlabel('Area')
plt.ylabel('Price' )
plt.title('House Prices')
plt.scatter(df.Area,df.Price,color='red',marker='+')

reg=LinearRegression()
reg.fit(df[['Area']],df.Price)

reg.predict([[3003]])