# -*- coding: utf-8 -*-
"""m_house_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7d_OWwj7Ih5gUJ7vlUNVddI0M0XwLXW
"""

!pip install numpy pandas matplotlib scikit-learn

#importing requried modules from python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

#loading dataset to the function
df=pd.read_csv("house_data_200.csv")
df.head(10)

print(df.columns)

m_price=df['Price'].median()

df=df.fillna(m_price,inplace=True)#it is used to fill (NaN) valuse with median value of price

import pandas as pd
from sklearn.linear_model import LinearRegression

# Load your data (assuming it's already cleaned)
df = pd.read_csv('house_data_200.csv')

# Define X and y
X = df[['Area', 'Bedrooms', 'Age']]
y = df['Price']

# Create and fit model
reg = LinearRegression()
reg.fit(X, y)

reg.predict([[1500,3,18]])